### ISSUE TITLE
Tube definition

### ISSUE THREAD

**Issue by rhpetry** [BDI-UFRGS/O3POntology#5]
O3PO:tube has O3PO:nozzle as subclass, and is defined as "def. a functional complex that is enclosed and hollow and that acts as a passageway to carry different sorts of things (e.g., fluids, cables, other ducts)".

There is no reason to believe a pipe fitting, hose, or any other enclosed and hollow element that allows the passageway of fluid should not be a tube too.

One could argue even open valves and open line blinds adhere to this description

**Comment by n0santos** [comment]
I modified the definition of tube by adding "long" to the description. Also moved nozzle to the material artifact class.
