### ISSUE TITLE
Fluid definition and equipment 

### ISSUE THREAD

**Issue by rhpetry** [BDI-UFRGS/O3POntology#6]
Some sources differentiate pumps (that pressurize liquids) and compressors (that pressurize gas), and currently there is no way of differentiating the intended type of fluid being pressurized by O3PO:Pump. When bringing oil to the surface, we work with solids, liquids, and gases, but some pumps are specially designed to only work with gases or liquids.

**Comment by n0santos** [comment]
Britannica: A pump is a device that expends energy to raise, transport, or compress fluids—liquids, and gases. Indeed there is no differentiation of types of pumps based on the type of material they transport. I don't see why we should do that actually.
